name: Deploy to Vercel

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.16.0"

      - name: Install Vercel CLI (working version)
        run: npm install --global vercel@latest

      - name: Print environment and versions
        run: |
          node -v
          npm -v
          npx vercel --version

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Prevent Vercel CLI from reinstalling deps
        run: |
          echo "node_modules" > .vercelignore
          echo ".vercel" >> .vercelignore
          # echo "package.json" >> .vercelignore
          # echo "package-lock.json" >> .vercelignore

      - name: Build Project using Next.js
        run: npm run build

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

